export { default as Kontakt } from './Kontakt.vue'
export { default as Oferta } from './Oferta.vue'
export { default as Start } from './Start.vue'
export { default as Portfolio } from './Portfolio.vue'
export { default as Projekt } from './Projekt.vue'
export { default as Prywatnosc } from './Prywatnosc.vue'
export { default as NotFound } from './NotFound.vue'