export { default as Kontakt } from './Kontakt.vue'
export { default as Oferta } from './Oferta.vue'
export { default as Start } from './Start.vue'
export { default as Portfolio } from './Portfolio.vue'
export { default as Projekt } from './Projekt.vue'
export { default as Prywatnosc } from './Prywatnosc.vue'
export { default as NotFound } from './NotFound.vue'

export { default as Login } from './Login.vue'
export { default as Dashboard } from './Dashboard.vue'

export { default as Overview } from './Admin/Overview.vue'
export { default as Emailing } from './Admin/Emailing.vue'
export { default as Analitics } from './Admin/Analitics.vue'
export { default as ExternalLinks } from './Admin/ExternalLinks.vue'
