export { default as Hero } from './Hero/Hero.vue'
export { default as OurWorks } from './OurWorks/OurWorks.vue'
export { default as AboutUs } from './AboutUs/AboutUs.vue'
export { default as WhyUs } from './WhyUs/WhyUs.vue'
export { default as ContactUs } from './ContactUs/ContactUs.vue'
export { default as Collabs } from './Collabs/Collabs.vue'
export { default as Footer } from './Footer/Footer.vue'
export { default as TypedHero } from './TypedHero/TypedHero.vue'
export { default as OurProcess } from './OurProcess/OurProcess.vue'
export { default as EmailForm } from './EmailForm/EmailForm.vue'
export { default as PortfolioGrid } from './PortfolioGrid/PortfolioGrid.vue'

export { default as ProjectHero } from './Project/ProjectHero/ProjectHero.vue'
export { default as ProjectInfo } from './Project/ProjectInfo/ProjectInfo.vue'
export { default as ProjectImages } from './Project/ProjectImages/ProjectImages.vue'